name: Release new version

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
          - custom
      release_branch:
        description: "Release branch"
        required: true
        type: string
        default: ""
      custom_version:
        description: "Custom version (only if 'custom' is selected above)"
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  release:
    uses: 4ndrs/shared-actions-testing/.github/workflows/reusable-release.yml@v3
    with:
      release_type: ${{ inputs.release_type }}
      release_branch: ${{ inputs.release_branch }}
      custom_version: ${{ inputs.custom_version }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
